### ISSUE TITLE
Executable built with pyinstaller does not work

### ISSUE THREAD

**Issue by maehw** [maehw/ms-teams-hand-detector#1]
Hi! 

I am currently trying to build an executable locally. The machine I am running on is a MacBook Air running MaOS. Building the executable works:

```
% pyinstaller ms_teams_hand_detector.py 
63 INFO: PyInstaller: 4.6
63 INFO: Python: 3.9.7
76 INFO: Platform: macOS-12.0.1-x86_64-i386-64bit
77 INFO: wrote /Users/matthias/local_repos/ms-teams-hand-detector/ms_teams_hand_detector.spec
81 INFO: UPX is not available.
83 INFO: Extending PYTHONPATH with paths
['/Users/matthias/local_repos/ms-teams-hand-detector']
313 INFO: checking Analysis
342 INFO: checking PYZ
350 INFO: EXE target arch: x86_64
...
```

However, calling the executable from the `dist` folder yields the following error message when being executed.

```
% ./ms_teams_hand_detector 
Traceback (most recent call last):
  File "ms_teams_hand_detector.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "cv2/__init__.py", line 180, in <module>
  File "cv2/__init__.py", line 110, in bootstrap
  File "cv2/__init__.py", line 108, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
[923] Failed to execute script 'ms_teams_hand_detector' due to unhandled exception!
```

Any OpenCV / Python / PyInstaller experts?
Any hints how this could be fixed?
(BTW: I think about using github's CI to generate executables automatically for Windows, Linux and Mac OS)

**Comment by maehw** [comment]
Related:

* https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/110
* https://github.com/marcelotduarte/cx_Freeze/issues/1275
